name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Gulp build
      run: npm run gulp build

    - name: Push to Deploy branch
      run: |
        git config --global user.email "di.project.moscow@gmail.com"
        git config --global user.name "Di-project"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
        git checkout -b Deploy
        git add -f path/to/your/build
        git commit -m "Deploy from master"
        git push origin Deploy --force
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Deploy branch
      uses: actions/checkout@v2
      with:
        ref: Deploy

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -r ./dist cg35166@185.114.247.198:/home/c/cg35166
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}